# Server configuration
application:
  ip_address: "127.0.0.1"
  port: 8091
  log_level: "info"
  token_secret: "Super_Secret4_Key"

# Postgres database config
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "postgres"
  require_ssl: false