# Server configuration
application:
  port: 8091
  address: "127.0.0.1"
  log_level: "info"

# Postgres database config
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "personal_ledger"
  require_ssl: false