# Server configuration
application:
  port: 8081
  ip_address: "0.0.0.0"
  log_level: "debug"

# Postgres database config
database:
  host: "postgres"
  port: 5432
  username: "authentication"
  password: "authentication"
  database_name: "authentication"
  require_ssl: false